DROP TABLE IF EXISTS MINICUBE;

CREATE TABLE MINICUBE (
  DIM_THE_DATE      INT            NOT NULL,
  DIM_TRADEID       INT            NOT NULL,
  DIM_PRODUCTLINEID INT            NOT NULL,
  DIM_POSTID        INT            NOT NULL,
  CSM               DECIMAL(11, 8) NOT NULL,
  CASH              DECIMAL(10, 8) NOT NULL,
  CLICK             BIGINT         NOT NULL,
  SHW               BIGINT         NOT NULL,
  _MERGE_FLAG_      INT            NOT NULL,
  PRIMARY KEY (DIM_THE_DATE, DIM_TRADEID, DIM_PRODUCTLINEID, DIM_POSTID)
);
